version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DYNAMODB_SHARE_DB=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"